/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Account Route */
        delete: operations["delete_account_route_api_v1_account_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Route */
        post: operations["login_route_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout Route */
        post: operations["logout_route_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout All Route */
        post: operations["logout_all_route_api_v1_auth_logout_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me Route */
        get: operations["get_me_route_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot Password Route */
        post: operations["forgot_password_route_api_v1_auth_password_forgot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password Route */
        post: operations["reset_password_route_api_v1_auth_password_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/verify-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Code Route */
        post: operations["verify_code_route_api_v1_auth_password_verify_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Route */
        post: operations["refresh_route_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Route */
        post: operations["register_route_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/social/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Social Sign In Route */
        post: operations["social_sign_in_route_api_v1_auth_social__provider__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/body-weight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Body Weight Route */
        get: operations["list_body_weight_route_api_v1_body_weight_get"];
        /** Upsert Body Weight Route */
        put: operations["upsert_body_weight_route_api_v1_body_weight_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/body-weight/{measured_on}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Body Weight Route */
        delete: operations["delete_body_weight_route_api_v1_body_weight__measured_on__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Route */
        get: operations["get_dashboard_route_api_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exercises Route */
        get: operations["list_exercises_route_api_v1_exercises_get"];
        put?: never;
        /** Create Exercise Route */
        post: operations["create_exercise_route_api_v1_exercises_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exercises/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exercise Route */
        get: operations["get_exercise_route_api_v1_exercises__exercise_id__get"];
        put?: never;
        post?: never;
        /** Delete Exercise Route */
        delete: operations["delete_exercise_route_api_v1_exercises__exercise_id__delete"];
        options?: never;
        head?: never;
        /** Update Exercise Route */
        patch: operations["update_exercise_route_api_v1_exercises__exercise_id__patch"];
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile Route */
        get: operations["get_profile_route_api_v1_profile_get"];
        put?: never;
        /** Create Profile Route */
        post: operations["create_profile_route_api_v1_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        /** Update Profile Route */
        patch: operations["update_profile_route_api_v1_profile_patch"];
        trace?: never;
    };
    "/api/v1/program": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Program Route */
        get: operations["get_current_program_route_api_v1_program_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/program/days/{day_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Program Day Route */
        get: operations["get_program_day_route_api_v1_program_days__day_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/program/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Program Route */
        post: operations["generate_program_route_api_v1_program_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Records Route */
        get: operations["get_records_route_api_v1_records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Workouts Route
         * @description §5.9 history. No rate limit: §7.3's table names `/workouts (POST)` and
         *     `/workouts/*\/sets`, neither of which is this route -- the same "enforce only what
         *     §7.3 actually names" rule `_rate_limited_for_start`'s docstring states.
         *
         *     `from`/`to` are aliased exactly as routers/body_weight.py aliases its own, since
         *     `from` is a Python keyword and cannot be a parameter name.
         */
        get: operations["list_workouts_route_api_v1_workouts_get"];
        put?: never;
        /** Start Workout Route */
        post: operations["start_workout_route_api_v1_workouts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workouts/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Active Workout Route
         * @description §5.1: "the in-progress session, or 204." `response_model=None` so FastAPI
         *     passes a raw 204 Response straight through instead of trying to validate it
         *     against a body-carrying model.
         */
        get: operations["get_active_workout_route_api_v1_workouts_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workouts/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workout Route
         * @description §5.9 detail. Declared after `/active` above, so FastAPI matches the literal
         *     path first -- a `{session_id}` route declared earlier would swallow `/active` and
         *     turn it into a 404 SESSION_NOT_FOUND for a malformed uuid.
         */
        get: operations["get_workout_route_api_v1_workouts__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workouts/{session_id}/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abandon Workout Route */
        post: operations["abandon_workout_route_api_v1_workouts__session_id__abandon_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workouts/{session_id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish Workout Route */
        post: operations["finish_workout_route_api_v1_workouts__session_id__finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workouts/{session_id}/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Set Route */
        post: operations["create_set_route_api_v1_workouts__session_id__sets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workouts/{session_id}/sets/{set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Set Route */
        delete: operations["delete_set_route_api_v1_workouts__session_id__sets__set_id__delete"];
        options?: never;
        head?: never;
        /** Update Set Route */
        patch: operations["update_set_route_api_v1_workouts__session_id__sets__set_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthMeResponse
         * @description §5.7: "One round trip decides the whole navigation state." `profile` is null
         *     until onboarding completes, then the same shape POST/GET/PATCH /profile return.
         */
        AuthMeResponse: {
            /** Onboarding Completed */
            onboarding_completed: boolean;
            profile: components["schemas"]["ProfileData"] | null;
            user: components["schemas"]["AuthMeUser"];
        };
        /**
         * AuthMeUser
         * @description §5.7's `user` object. `auth_methods` lists "password" (if a password is set)
         *     followed by every linked social provider -- see auth_service.get_me.
         */
        AuthMeUser: {
            /** Auth Methods */
            auth_methods: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Email Verified */
            email_verified: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** BestE1rmData */
        BestE1rmData: {
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /** Reps */
            reps: number;
            /** Value Kg */
            value_kg: number;
            /** Weight Kg */
            weight_kg: number;
        };
        /** BestSessionVolumeData */
        BestSessionVolumeData: {
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Volume Kg */
            volume_kg: number;
        };
        /**
         * BodyWeightEntryData
         * @description The full row shape -- PUT's own `entry` object.
         */
        BodyWeightEntryData: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Measured On
             * Format: date
             */
            measured_on: string;
            /** Note */
            note: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Weight Kg */
            weight_kg: number;
        };
        /** BodyWeightListResponse */
        BodyWeightListResponse: {
            /** Entries */
            entries: components["schemas"]["BodyWeightPoint"][];
            /** Moving Average 7D */
            moving_average_7d: components["schemas"]["BodyWeightPoint"][];
            summary: components["schemas"]["BodyWeightSummaryData"];
        };
        /**
         * BodyWeightPoint
         * @description §5.10 GET's own worked example shape, shared by `entries` and
         *     `moving_average_7d` -- both are lean `{measured_on, weight_kg}` pairs, nothing more.
         */
        BodyWeightPoint: {
            /**
             * Measured On
             * Format: date
             */
            measured_on: string;
            /** Weight Kg */
            weight_kg: number;
        };
        /**
         * BodyWeightSummaryData
         * @description §5.10's `summary` block. All four are null/zero on an empty range -- there is no
         *     entry to report `first`/`latest`/`change_kg` from, and that is a well-formed 200,
         *     not an error (P2-FR-009 is a log the caller may legitimately have zero rows in for
         *     any given window, unlike GET /program's "never generated one" 404).
         */
        BodyWeightSummaryData: {
            /** Change Kg */
            change_kg: number | null;
            /** Entry Count */
            entry_count: number;
            /** First */
            first: number | null;
            /** Latest */
            latest: number | null;
        };
        /**
         * BodyWeightUpsertRequest
         * @description §5.10 PUT. `note` defaults to `None` -- PUT is a full replace (P2-ADR-06: "same-day
         *     writes replace"), so an omitted `note` clears one exactly the same as an explicit
         *     `null` would, matching the wire example's own `"note": null`.
         */
        BodyWeightUpsertRequest: {
            /** Measured On */
            measured_on: string;
            /** Note */
            note?: string | null;
            /** Weight Kg */
            weight_kg: number | string;
        };
        /** BodyWeightUpsertResponse */
        BodyWeightUpsertResponse: {
            entry: components["schemas"]["BodyWeightEntryData"];
            /** Profile Weight Updated */
            profile_weight_updated: boolean;
        };
        /** DashboardResponse */
        DashboardResponse: {
            active_session: components["schemas"]["WorkoutSessionSummary"] | null;
            /** Disclaimer Key */
            disclaimer_key: string;
            /** Greeting Name */
            greeting_name: string;
            next_workout: components["schemas"]["NextWorkoutData"] | null;
            /** Program Stale */
            program_stale: {
                [key: string]: string;
            } | null;
            /** Recent Records */
            recent_records: components["schemas"]["RecentRecordData"][];
            streak: components["schemas"]["StreakData"];
            this_week: components["schemas"]["ThisWeekData"];
            /** Weight */
            weight: {
                [key: string]: unknown;
            };
        };
        /**
         * DeleteAccountRequest
         * @description §5.10: "password required when password_hash is not null; omitted for
         *     social-only accounts." `password` is optional at the schema level -- whether it
         *     is actually required depends on the authenticated user's row, which the schema
         *     cannot see, so auth_service.delete_account enforces that. A social-only caller
         *     still sends a JSON object (`{}`); FastAPI has no body to parse from a request
         *     with no content at all, only from an empty object.
         */
        DeleteAccountRequest: {
            /** Password */
            password?: string | null;
        };
        /**
         * DeleteAccountResponse
         * @description §5.10's exact 202 shape.
         */
        DeleteAccountResponse: {
            /**
             * Deletion Requested At
             * Format: date-time
             */
            deletion_requested_at: string;
            /**
             * Purge After Days
             * @default 30
             */
            purge_after_days: number;
        };
        /**
         * DerivedFields
         * @description §5.8: "age is computed, never stored."
         */
        DerivedFields: {
            /** Age */
            age: number;
        };
        /**
         * ExerciseCreateRequest
         * @description POST /exercises. One `name`, in whichever language the user typed -- see
         *     `exercise_repo.create_custom` for why it is written to both name columns rather than
         *     translated or left blank.
         *
         *     Every closed-vocabulary field is a bare `str` here and validated in the router
         *     against models/exercise.py's exported tuples, the same tuples the CHECK constraints
         *     are built from. Typing them as Literal/Enum would move the failure into pydantic and
         *     produce FastAPI's 422 body instead of §7.2's envelope with a per-field code.
         */
        ExerciseCreateRequest: {
            /** Difficulty */
            difficulty: string;
            /** Equipment */
            equipment: string;
            /**
             * Instructions
             * @default
             */
            instructions: string;
            /**
             * Is Compound
             * @default false
             */
            is_compound: boolean;
            /** Movement Pattern */
            movement_pattern: string;
            /** Name */
            name: string;
            /** Primary Muscle */
            primary_muscle: string;
            /** Secondary Muscles */
            secondary_muscles?: string[];
        };
        /**
         * ExerciseDeleteResponse
         * @description §5.2's soft delete: the row stays resolvable by id for sessions that logged it,
         *     so the response reports what actually happened rather than an empty 204 that would
         *     imply the row is gone.
         */
        ExerciseDeleteResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * ExerciseDetail
         * @description §5.2: "GET /exercises/{id} additionally returns instructions."
         */
        ExerciseDetail: {
            /** Difficulty */
            difficulty: string;
            /** Equipment */
            equipment: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Instructions */
            instructions: string;
            /** Is Compound */
            is_compound: boolean;
            /** Is Custom */
            is_custom: boolean;
            /** Movement Pattern */
            movement_pattern: string;
            /** Name */
            name: string;
            /** Primary Muscle */
            primary_muscle: string;
            /** Secondary Muscles */
            secondary_muscles: string[];
            /** Slug */
            slug: string;
        };
        /** ExerciseDetailResponse */
        ExerciseDetailResponse: {
            exercise: components["schemas"]["ExerciseDetail"];
        };
        /**
         * ExerciseListItem
         * @description §5.2: `name` is resolved server-side from the caller's profile language -- the
         *     one deliberate exception to "the server never sends display text" (Phase 1 §9.6),
         *     made because shipping both languages' names to every client for a ~60-row library
         *     doubles the payload for no client that ever shows both at once.
         */
        ExerciseListItem: {
            /** Difficulty */
            difficulty: string;
            /** Equipment */
            equipment: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Compound */
            is_compound: boolean;
            /** Is Custom */
            is_custom: boolean;
            /** Movement Pattern */
            movement_pattern: string;
            /** Name */
            name: string;
            /** Primary Muscle */
            primary_muscle: string;
            /** Secondary Muscles */
            secondary_muscles: string[];
            /** Slug */
            slug: string;
        };
        /** ExerciseListResponse */
        ExerciseListResponse: {
            /** Items */
            items: components["schemas"]["ExerciseListItem"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * ExerciseUpdateRequest
         * @description PATCH /exercises/{id}. Every field optional; only what is sent is changed. `None`
         *     means "not sent" rather than "clear it" -- none of these columns is nullable, so
         *     there is nothing a client could legitimately clear.
         */
        ExerciseUpdateRequest: {
            /** Difficulty */
            difficulty?: string | null;
            /** Equipment */
            equipment?: string | null;
            /** Instructions */
            instructions?: string | null;
            /** Is Compound */
            is_compound?: boolean | null;
            /** Movement Pattern */
            movement_pattern?: string | null;
            /** Name */
            name?: string | null;
            /** Primary Muscle */
            primary_muscle?: string | null;
            /** Secondary Muscles */
            secondary_muscles?: string[] | null;
        };
        /**
         * ForgotPasswordRequest
         * @description §5.6 call 1. `email` is the only field -- deliberately unauthenticated.
         */
        ForgotPasswordRequest: {
            /** Email */
            email: string;
        };
        /**
         * ForgotPasswordResponse
         * @description §5.6: the exact same body regardless of whether the account exists.
         */
        ForgotPasswordResponse: {
            /**
             * Message
             * @default If an account exists for that address, a code has been sent.
             */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeaviestSetData */
        HeaviestSetData: {
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /** Reps */
            reps: number;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Weight Kg */
            weight_kg: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * LogoutRequest
         * @description §5's /auth/logout. The access token identifies the caller; it carries no
         *     family_id (P1-ADR-02's claim list), so the refresh token is what tells the server
         *     which family to revoke.
         */
        LogoutRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** NextWorkoutData */
        NextWorkoutData: {
            /** Day Index */
            day_index: number;
            /** Estimated Minutes */
            estimated_minutes: number;
            /** Exercise Count */
            exercise_count: number;
            /** Label Key */
            label_key: string;
            /**
             * Program Day Id
             * Format: uuid
             */
            program_day_id: string;
        };
        /**
         * ProfileCreateRequest
         * @description §5.8. birth_date is a plain str (not a pydantic `date`), deliberately -- see the
         *     module docstring: a malformed date string must reach profile_service as a
         *     VALIDATION_ERROR, not FastAPI's default body.
         */
        ProfileCreateRequest: {
            /** Activity Level */
            activity_level?: string | null;
            /** Birth Date */
            birth_date: string;
            /** Experience Level */
            experience_level: string;
            /** Gender */
            gender: string;
            /** Goal */
            goal: string;
            /** Height Cm */
            height_cm: number | string;
            /**
             * Language
             * @default ar
             */
            language: string;
            /** Name */
            name: string;
            /**
             * Unit System
             * @default metric
             */
            unit_system: string;
            /** Weight Kg */
            weight_kg?: number | string | null;
        };
        /** ProfileCreateResponse */
        ProfileCreateResponse: {
            derived: components["schemas"]["DerivedFields"];
            profile: components["schemas"]["ProfileData"];
        };
        /**
         * ProfileData
         * @description The full profile object shape shared by /auth/me, and the POST/GET/PATCH
         *     /profile responses (§5.7, §5.8, §5.9).
         */
        ProfileData: {
            /** Activity Level */
            activity_level: string | null;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Experience Level */
            experience_level: string;
            /** Gender */
            gender: string;
            /** Goal */
            goal: string;
            /** Height Cm */
            height_cm: number;
            /** Language */
            language: string;
            /** Name */
            name: string;
            /** Onboarding Completed */
            onboarding_completed: boolean;
            /** Timezone */
            timezone: string;
            /** Unit System */
            unit_system: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Weight Kg */
            weight_kg: number | null;
        };
        /** ProfileResponse */
        ProfileResponse: {
            profile: components["schemas"]["ProfileData"];
        };
        /**
         * ProfileUpdateRequest
         * @description §5.9's editable/immutable table. Every field is optional so `model_dump(
         *     exclude_unset=True)` in profile_service tells "not sent" from "sent", which is what
         *     "only the keys present in the body are touched" (partial update) requires.
         *
         *     `onboarding_completed` is declared explicitly, and only so `extra="forbid"` does not
         *     reject it -- §5.9: "Server-controlled. A client sending it is ignored, not
         *     rejected." profile_service never reads this field.
         */
        ProfileUpdateRequest: {
            /** Activity Level */
            activity_level?: string | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Experience Level */
            experience_level?: string | null;
            /** Gender */
            gender?: string | null;
            /** Goal */
            goal?: string | null;
            /** Height Cm */
            height_cm?: number | string | null;
            /** Language */
            language?: string | null;
            /** Name */
            name?: string | null;
            /** Onboarding Completed */
            onboarding_completed?: boolean | null;
            /** Timezone */
            timezone?: string | null;
            /** Unit System */
            unit_system?: string | null;
            /** Weight Kg */
            weight_kg?: number | string | null;
        };
        /** ProgramDayDetail */
        ProgramDayDetail: {
            /** Day Index */
            day_index: number;
            /** Exercises */
            exercises: components["schemas"]["ProgramDayExerciseDetail"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label Key */
            label_key: string;
        };
        /** ProgramDayDetailResponse */
        ProgramDayDetailResponse: {
            day: components["schemas"]["ProgramDayDetail"];
        };
        /**
         * ProgramDayExerciseBestSet
         * @description §5.5's `last_performance.best_set` -- reps and weight only, matching the spec's
         *     own worked example exactly.
         */
        ProgramDayExerciseBestSet: {
            /** Reps */
            reps: number;
            /** Weight Kg */
            weight_kg: number;
        };
        /** ProgramDayExerciseDetail */
        ProgramDayExerciseDetail: {
            exercise: components["schemas"]["ProgramDayExerciseRef"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            last_performance: components["schemas"]["ProgramDayExerciseLastPerformance"] | null;
            /** Position */
            position: number;
            /** Rest Seconds */
            rest_seconds: number;
            /** Target Reps Max */
            target_reps_max: number;
            /** Target Reps Min */
            target_reps_min: number;
            /** Target Sets */
            target_sets: number;
        };
        /**
         * ProgramDayExerciseLastPerformance
         * @description §5.5's `last_performance` -- the most recent COMPLETED session (P2-ADR-04)
         *     containing at least one non-warm-up set of this exercise. "Best" is not defined by
         *     the spec's own wording beyond showing the field; `program_service.
         *     _resolve_last_performance` is where that decision is made (highest e1RM, tie-broken
         *     on heavier weight_kg, then on earliest logged_at) -- this schema only carries the
         *     result of it.
         */
        ProgramDayExerciseLastPerformance: {
            best_set: components["schemas"]["ProgramDayExerciseBestSet"];
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /**
         * ProgramDayExerciseRef
         * @description §5.5's nested `exercise` object -- deliberately narrower than
         *     schemas/exercise.py's ExerciseListItem; the spec's own example shows exactly these
         *     five fields and no more.
         */
        ProgramDayExerciseRef: {
            /** Equipment */
            equipment: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Primary Muscle */
            primary_muscle: string;
            /** Slug */
            slug: string;
        };
        /**
         * ProgramDaySummary
         * @description §5.3/§5.4: a day inside the program object -- summary only, `exercise_count`
         *     rather than the exercise list itself. `GET /program/days/{day_id}` (below) is where
         *     a day's full exercise list lives.
         */
        ProgramDaySummary: {
            /** Day Index */
            day_index: number;
            /** Estimated Minutes */
            estimated_minutes: number;
            /** Exercise Count */
            exercise_count: number;
            /** Focus Muscles */
            focus_muscles: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label Key */
            label_key: string;
        };
        /** ProgramGenerateRequest */
        ProgramGenerateRequest: {
            /** Days Per Week */
            days_per_week: number;
        };
        /** ProgramGenerateResponse */
        ProgramGenerateResponse: {
            /** Notes Key */
            notes_key: string[];
            program: components["schemas"]["ProgramSummary"];
        };
        /** ProgramResponse */
        ProgramResponse: {
            program: components["schemas"]["ProgramSummary"];
            /** Stale */
            stale: {
                [key: string]: string;
            } | null;
        };
        /** ProgramSummary */
        ProgramSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Days */
            days: components["schemas"]["ProgramDaySummary"][];
            /** Days Per Week */
            days_per_week: number;
            /** Experience Level */
            experience_level: string;
            /** Generator Version */
            generator_version: number;
            /** Goal */
            goal: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Split Type */
            split_type: string;
        };
        /** RecentRecordData */
        RecentRecordData: {
            /** Exercise Name */
            exercise_name: string;
            /** Kind */
            kind: string;
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /** Value */
            value: number;
        };
        /** RecordEntryData */
        RecordEntryData: {
            best_e1rm: components["schemas"]["BestE1rmData"];
            best_session_volume: components["schemas"]["BestSessionVolumeData"];
            exercise: components["schemas"]["RecordExerciseRef"];
            heaviest_set: components["schemas"]["HeaviestSetData"];
            /** Total Sets */
            total_sets: number;
        };
        /** RecordExerciseRef */
        RecordExerciseRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /**
         * RecordSetItem
         * @description §5.8's `records_set` array element -- computed at read time over
         *     `workout_sets` (P2-ADR-05), never stored. `kind` is always `"e1rm"`, the same
         *     single kind T-19's in-session `is_record` (`SetRecordData` below) already uses.
         */
        RecordSetItem: {
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Kind */
            kind: string;
            /** Value */
            value: number;
        };
        /** RecordsResponse */
        RecordsResponse: {
            /** Records */
            records: components["schemas"]["RecordEntryData"][];
        };
        /**
         * RefreshRequest
         * @description §5.5. The opaque refresh token is the only field -- there is no bearer here.
         */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Email */
            email: string;
            /**
             * Language
             * @default ar
             */
            language: string;
            /** Password */
            password: string;
        };
        /**
         * ResetPasswordRequest
         * @description §5.6 call 3. No email here -- the reset token alone identifies the account.
         */
        ResetPasswordRequest: {
            /** New Password */
            new_password: string;
            /** Reset Token */
            reset_token: string;
        };
        /**
         * SessionDetailExerciseGroup
         * @description §5.9: sets "grouped by exercise in `position` order for a plan-backed session
         *     and in first-logged order for an empty one.
         */
        SessionDetailExerciseGroup: {
            exercise: components["schemas"]["SessionDetailExerciseRef"];
            /** Sets */
            sets: components["schemas"]["WorkoutSetData"][];
        };
        /**
         * SessionDetailExerciseRef
         * @description The exercise a detail group names. Same narrow shape as schemas/program.py's
         *     `ProgramDayExerciseRef`, minus `equipment` -- a past session's read-only view needs
         *     to name the movement, not describe how to set it up.
         */
        SessionDetailExerciseRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Primary Muscle */
            primary_muscle: string;
            /** Slug */
            slug: string;
        };
        /** SessionTotalsData */
        SessionTotalsData: {
            /** Sets */
            sets: number;
            /** Volume Kg */
            volume_kg: number;
        };
        /**
         * SetDerived
         * @description §5.7's `derived` block -- computed fresh every time (P2-ADR-04): never stored.
         */
        SetDerived: {
            /** E1Rm Kg */
            e1rm_kg: number;
            /** Volume Kg */
            volume_kg: number;
        };
        /** SetRecordData */
        SetRecordData: {
            /** Kind */
            kind: string;
            /** Previous */
            previous: number;
        };
        /**
         * SocialSignInRequest
         * @description §5.4. "The body carries exactly one field: id_token." Deliberately NOT
         *     extra="forbid" like this module's other request schemas: §5.4's own security note --
         *     "the provider, the uid, and the email all come from the verified token -- never from
         *     the request body" -- means an attacker-supplied `email` or `provider` alongside a
         *     valid id_token must be silently ignored, not rejected as an unknown field. See
         *     test_social_auth.py's body-field-ignored control test.
         */
        SocialSignInRequest: {
            /** Id Token */
            id_token: string;
        };
        /**
         * SocialSignInResponse
         * @description §5.4: identical shape to register/login's token pair, plus is_new_user so the
         *     client knows whether to route to onboarding or home.
         */
        SocialSignInResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /** Is New User */
            is_new_user: boolean;
            /** Refresh Expires In */
            refresh_expires_in: number;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserSummary"];
        };
        /** StreakData */
        StreakData: {
            /** Current Days */
            current_days: number;
            /** Last Workout Local Date */
            last_workout_local_date: string | null;
            /** Longest Days */
            longest_days: number;
        };
        /** ThisWeekData */
        ThisWeekData: {
            /** Completed */
            completed: number;
            /**
             * Local Week Start
             * Format: date
             */
            local_week_start: string;
            /** Target */
            target: number;
        };
        /**
         * TokenPairResponse
         * @description Identical shape for register (§5.2) and login (§5.3).
         */
        TokenPairResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /** Refresh Expires In */
            refresh_expires_in: number;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserSummary"];
        };
        /** UserSummary */
        UserSummary: {
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Onboarding Completed */
            onboarding_completed: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerifyCodeRequest
         * @description §5.6 call 2. `code` is validated by attempting a match, not by a schema-level
         *     shape check -- see password_reset_service: a malformed code cannot match any
         *     stored digest, so it already surfaces as RESET_CODE_INVALID (§7.1) through the
         *     same path a wrong-but-well-formed code takes, with no separate rule to keep in
         *     sync with P1-ADR-07's alphabet.
         */
        VerifyCodeRequest: {
            /** Code */
            code: string;
            /** Email */
            email: string;
        };
        /**
         * VerifyCodeResponse
         * @description §5.6: opaque, single-purpose, single-use, 5 minutes.
         */
        VerifyCodeResponse: {
            /** Expires In */
            expires_in: number;
            /** Reset Token */
            reset_token: string;
        };
        /** WorkoutAbandonResponse */
        WorkoutAbandonResponse: {
            session: components["schemas"]["WorkoutFinishedSummary"];
        };
        /**
         * WorkoutDetailData
         * @description §5.9: "the session with every set." `notes` is the caller's own note on their
         *     own session -- §11.1's security test asserts no endpoint returns *another* user's,
         *     which the route's ownership scoping is what guarantees.
         */
        WorkoutDetailData: {
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Ended At */
            ended_at: string | null;
            /** Exercise Count */
            exercise_count: number;
            /** Exercises */
            exercises: components["schemas"]["SessionDetailExerciseGroup"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label Key */
            label_key: string | null;
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /** Notes */
            notes: string | null;
            /** Program Day Id */
            program_day_id: string | null;
            /** Records Set */
            records_set: components["schemas"]["RecordSetItem"][];
            /** Set Count */
            set_count: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
            /** Total Volume Kg */
            total_volume_kg: number | null;
        };
        /** WorkoutDetailResponse */
        WorkoutDetailResponse: {
            session: components["schemas"]["WorkoutDetailData"];
        };
        /** WorkoutFinishRequest */
        WorkoutFinishRequest: {
            /** Notes */
            notes?: string | null;
        };
        /** WorkoutFinishResponse */
        WorkoutFinishResponse: {
            /** Records Set */
            records_set: components["schemas"]["RecordSetItem"][];
            session: components["schemas"]["WorkoutFinishedSummary"];
        };
        /**
         * WorkoutFinishedSummary
         * @description §5.8's session object -- returned by both finish and abandon. Abandon leaves
         *     `duration_seconds`/`total_volume_kg` null: "abandon ... computes nothing" (§5.8),
         *     so those two fields on the row are whatever they already were (always NULL,
         *     since a session that never finished never had them set).
         */
        WorkoutFinishedSummary: {
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Ended At */
            ended_at: string | null;
            /** Exercise Count */
            exercise_count: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Set Count */
            set_count: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
            /** Total Volume Kg */
            total_volume_kg: number | null;
        };
        /**
         * WorkoutHistoryItem
         * @description §5.9: "summaries only -- id, `local_date`, status, duration, volume, set count,
         *     and the program day's `label_key`." Exactly those seven fields and no more: the
         *     sets themselves are what `GET /workouts/{id}` is for, and a history row that
         *     carried them would make the list's payload grow with the user's training volume.
         *
         *     `label_key` is null for a session started without a plan (§4.6's nullable
         *     `program_day_id`), never a translated string -- the server never sends display
         *     text (Phase 1 §9.6).
         */
        WorkoutHistoryItem: {
            /** Duration Seconds */
            duration_seconds: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label Key */
            label_key: string | null;
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /** Set Count */
            set_count: number;
            /** Status */
            status: string;
            /** Total Volume Kg */
            total_volume_kg: number | null;
        };
        /** WorkoutHistoryResponse */
        WorkoutHistoryResponse: {
            /** Items */
            items: components["schemas"]["WorkoutHistoryItem"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * WorkoutSessionSummary
         * @description §5.6's session object -- the shape POST /workouts and GET /workouts/active
         *     both return. `sets` is always `[]` here: no endpoint in this task can populate
         *     one (T-19 owns POST /workouts/{id}/sets and its response shape), the same kind
         *     of deliberate, documented placeholder schemas/program.py's
         *     `last_performance: None` is for the same T-18/T-19 gap.
         */
        WorkoutSessionSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /** Program Day Id */
            program_day_id: string | null;
            /**
             * Sets
             * @default []
             */
            sets: unknown[];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
        };
        /**
         * WorkoutSetActionResponse
         * @description §5.7's POST response shape, reused for PATCH: both mutate a set and both need
         *     the same freshly computed `derived`/`session_totals`/`is_record` triple
         *     (P2-ADR-04: computed on read, never stored -- there is no reason POST's row gets
         *     fresher numbers than PATCH's edited one).
         */
        WorkoutSetActionResponse: {
            is_record: components["schemas"]["SetRecordData"] | null;
            session_totals: components["schemas"]["SessionTotalsData"];
            set: components["schemas"]["WorkoutSetData"];
        };
        /**
         * WorkoutSetCreateRequest
         * @description §5.7 POST. `exercise_id` stays a bare `str` -- see the module docstring.
         */
        WorkoutSetCreateRequest: {
            /** Exercise Id */
            exercise_id: string;
            /**
             * Is Warmup
             * @default false
             */
            is_warmup: boolean;
            /** Reps */
            reps: number;
            /** Rpe */
            rpe?: number | string | null;
            /** Weight Kg */
            weight_kg: number | string;
        };
        /** WorkoutSetData */
        WorkoutSetData: {
            derived: components["schemas"]["SetDerived"];
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Warmup */
            is_warmup: boolean;
            /**
             * Logged At
             * Format: date-time
             */
            logged_at: string;
            /** Reps */
            reps: number;
            /** Rpe */
            rpe: number | null;
            /** Set Index */
            set_index: number;
            /** Weight Kg */
            weight_kg: number;
        };
        /**
         * WorkoutSetPatchRequest
         * @description §5.7 PATCH: "Any of reps, weight_kg, rpe, is_warmup. Not exercise_id" --
         *     `exercise_id` has no field here at all, so `extra="forbid"` rejects it with
         *     FastAPI's own body-parsing error rather than a dedicated code, matching
         *     `ProfileUpdateRequest`/`WorkoutFinishRequest`'s own precedent for a field that
         *     must never be accepted. Every field optional, so `model_dump(exclude_unset=True)`
         *     in workout_service tells "not sent" from "sent" -- what a partial update needs
         *     (profile_service's `update_profile` sets the same convention).
         */
        WorkoutSetPatchRequest: {
            /** Is Warmup */
            is_warmup?: boolean | null;
            /** Reps */
            reps?: number | null;
            /** Rpe */
            rpe?: number | string | null;
            /** Weight Kg */
            weight_kg?: number | string | null;
        };
        /** WorkoutStartRequest */
        WorkoutStartRequest: {
            /** Program Day Id */
            program_day_id?: string | null;
        };
        /** WorkoutStartResponse */
        WorkoutStartResponse: {
            session: components["schemas"]["WorkoutSessionSummary"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    delete_account_route_api_v1_account_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteAccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_route_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_route_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_all_route_api_v1_auth_logout_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_me_route_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeResponse"];
                };
            };
        };
    };
    forgot_password_route_api_v1_auth_password_forgot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForgotPasswordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_route_api_v1_auth_password_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_code_route_api_v1_auth_password_verify_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyCodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_route_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_route_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_sign_in_route_api_v1_auth_social__provider__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SocialSignInRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialSignInResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_body_weight_route_api_v1_body_weight_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyWeightListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_body_weight_route_api_v1_body_weight_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BodyWeightUpsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyWeightUpsertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_body_weight_route_api_v1_body_weight__measured_on__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                measured_on: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_route_api_v1_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
        };
    };
    list_exercises_route_api_v1_exercises_get: {
        parameters: {
            query?: {
                muscle?: string | null;
                equipment?: string | null;
                q?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_exercise_route_api_v1_exercises_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exercise_route_api_v1_exercises__exercise_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_exercise_route_api_v1_exercises__exercise_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_exercise_route_api_v1_exercises__exercise_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_profile_route_api_v1_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
        };
    };
    create_profile_route_api_v1_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_route_api_v1_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_program_route_api_v1_program_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramResponse"];
                };
            };
        };
    };
    get_program_day_route_api_v1_program_days__day_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramDayDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_program_route_api_v1_program_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgramGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramGenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_records_route_api_v1_records_get: {
        parameters: {
            query?: {
                exercise_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workouts_route_api_v1_workouts_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                status?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_workout_route_api_v1_workouts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_workout_route_api_v1_workouts_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_workout_route_api_v1_workouts__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abandon_workout_route_api_v1_workouts__session_id__abandon_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutAbandonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_workout_route_api_v1_workouts__session_id__finish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutFinishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutFinishResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_set_route_api_v1_workouts__session_id__sets_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutSetCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSetActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_set_route_api_v1_workouts__session_id__sets__set_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_set_route_api_v1_workouts__session_id__sets__set_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                set_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutSetPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSetActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
